version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_DB: controle-financeiro
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  api:
      build: "./"
      container_name: controle-financeiro
      restart: always
      environment:
        JWT_SECRET: ${JWT_SECRET}
        DATASOURCE_URL: jdbc:postgresql://db:5432/controle-financeiro
        DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
        DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}

      ports:
        - "8080:8080"
      depends_on:
        - db